title: 쿼릭 Quorlyk
description: 정부지원금·세금·연금 같은 돈 정보와 생활 절차, 여행 정보를 공식 자료로 확인해 쉽게 정리하는 정보 사이트
url: https://quorlyk.com
lang: ko
permalink: /:title/
timezone: Asia/Seoul
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  - scope: {path: "", type: posts}
    values: {layout: post}
  - scope: {path: ""}
    values: {layout: page}
email: "quorlyk@daum.net"
